### ISSUE TITLE
What is the correct WETH-USDC Pool address on Ropsten?

### ISSUE THREAD

**Issue by Developer5600** [circlefin/stablecoin-evm#348]
I have tried both of these for pools:

```
//address WETHUSDCPool = 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640;
from https://etherscan.io/address/0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640#readContract -- this looks like the right pool from searching

  address WETHUSDCPool = 0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8; //?? linked from uniswap
from https://info.uniswap.org/#/pools/0x8ad599c3a0ff1de082011efddc58f1908eb6e6d -- this one I get from UNISWAP
```

I always get an error consulting the Uniswap V3 Oracle Library with these pools, it reverts which it can do if there are no reserves.

What is the correct WETH-USDC Pool? Thank you!!

**Comment by Developer5600** [comment]
The info I was getting from uniswap was a mainnet pool despite being connected to Ropsten in my metamask. Hm. How do I find the pool for WETH-USDC on Ropsten?

**Comment by Developer5600** [comment]
I found https://ropsten.etherscan.io/address/0x1F98431c8aD98523631AE4a59f267346ea31F984#code
and using  values 
0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 (USDC Ropsten)
0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 (WETH Ropsten)
and 3000 for the pool rate
I got "0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8"

this still always reverts when I do the Uniswap Oracle Library consult on it.

**Comment by Mehduzza420** [comment]
I am currently looking for it...my accounts have been severely compromised and I have to do a security check

**Comment by lazvegas13** [comment]
> 

No
