### ISSUE TITLE
I am currently looking for it...my accounts have been severely compromised and I have to do a security check

### ISSUE THREAD

**Issue by lazvegas13** [circlefin/stablecoin-evm#350]
I am currently looking for it...my accounts have been severely compromised and I have to do a security check

_Originally posted by @Mehduzza420 in https://github.com/centrehq/centre-tokens/issues/348#issuecomment-1100688252_

**Comment by Adminsupportteam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues 

https://direct.lc.chat/14201763/

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769
